import 'package:flutter/material.dart';
import 'cpk_standards.dart';

enum ElementCategory {
  nonmetal,
  nobleGas,
  alkaliMetal,
  alkalineEarthMetal,
  metalloid,
  halogen,
  transitionMetal,
  postTransitionMetal,
  lanthanide,
  actinide,
}

enum ElementAgronomicRole {
  macronutrient,
  micronutrient,
  beneficial,
  structural,
  toxic,
  inert,
}

class ElementInfo {
  final String symbol;
  final String nameEn;
  final String nameFi;
  final int atomicNumber;
  final double atomicMass;
  final int typicalCharge;
  final ElementCategory category;
  final ElementAgronomicRole agronomicRole;
  final String soilRoleEn;
  final String soilRoleFi;
  final int group;
  final int period;

  const ElementInfo({
    required this.symbol,
    required this.nameEn,
    required this.nameFi,
    required this.atomicNumber,
    required this.atomicMass,
    required this.typicalCharge,
    required this.category,
    this.agronomicRole = ElementAgronomicRole.inert,
    required this.soilRoleEn,
    required this.soilRoleFi,
    required this.group,
    required this.period,
  });

  /// Backward compatible default getters (defaults to English if locale is not supplied)
  String get name => nameEn;
  String get soilRole => soilRoleEn;

  /// Locale-aware element name
  String localizedName(String langCode) =>
      langCode.toLowerCase().startsWith('fi') ? nameFi : nameEn;

  /// Locale-aware soil and ecological description
  String localizedRole(String langCode) =>
      langCode.toLowerCase().startsWith('fi') ? soilRoleFi : soilRoleEn;

  /// Alias for localizedRole
  String localizedSoilRole(String langCode) => localizedRole(langCode);

  /// Localized category name
  String localizedCategory(String langCode) {
    final isFi = langCode.toLowerCase().startsWith('fi');
    switch (category) {
      case ElementCategory.nonmetal:
        return isFi ? 'Epämetalli' : 'Nonmetal';
      case ElementCategory.nobleGas:
        return isFi ? 'Jalokaasu' : 'Noble gas';
      case ElementCategory.alkaliMetal:
        return isFi ? 'Alkalimetalli' : 'Alkali metal';
      case ElementCategory.alkalineEarthMetal:
        return isFi ? 'Maa-alkalimetalli' : 'Alkaline earth metal';
      case ElementCategory.metalloid:
        return isFi ? 'Puolimetalli' : 'Metalloid';
      case ElementCategory.halogen:
        return isFi ? 'Halogeeni' : 'Halogen';
      case ElementCategory.transitionMetal:
        return isFi ? 'Siirtymämetalli' : 'Transition metal';
      case ElementCategory.postTransitionMetal:
        return isFi ? 'Jälkisiirtymämetalli' : 'Post-transition metal';
      case ElementCategory.lanthanide:
        return isFi ? 'Lantanoidi' : 'Lanthanide';
      case ElementCategory.actinide:
        return isFi ? 'Aktinoidi' : 'Actinide';
    }
  }

  /// Localized agronomic role badge
  String localizedAgronomicRole(String langCode) {
    final isFi = langCode.toLowerCase().startsWith('fi');
    switch (agronomicRole) {
      case ElementAgronomicRole.macronutrient:
        return isFi ? 'Pääravinne' : 'Macronutrient';
      case ElementAgronomicRole.micronutrient:
        return isFi ? 'Hivenravinne' : 'Micronutrient';
      case ElementAgronomicRole.beneficial:
        return isFi ? 'Hyödyllinen' : 'Beneficial';
      case ElementAgronomicRole.structural:
        return isFi ? 'Rakennealkuaine' : 'Structural';
      case ElementAgronomicRole.toxic:
        return isFi ? 'Myrkky / Saaste' : 'Toxic / Pollutant';
      case ElementAgronomicRole.inert:
        return isFi ? 'Reagoimaton' : 'Inert';
    }
  }

  /// CPK (Corey-Pauling-Koltun) standard color for this element.
  Color get cpkColor => CPKStandards.getColor(symbol);

  /// Default category-based color for the periodic table view.
  Color get color {
    switch (category) {
      case ElementCategory.nonmetal:
        return const Color(0xFF64748B); // Slate
      case ElementCategory.nobleGas:
        return const Color(0xFF94A3B8); // Light Slate
      case ElementCategory.alkaliMetal:
        return const Color(0xFFB91C1C); // Muted Red
      case ElementCategory.alkalineEarthMetal:
        return const Color(0xFFC2410C); // Muted Orange
      case ElementCategory.metalloid:
        return const Color(0xFF0F766E); // Muted Teal
      case ElementCategory.halogen:
        return const Color(0xFF1D4ED8); // Muted Blue
      case ElementCategory.transitionMetal:
        return const Color(0xFF701A75); // Muted Fuchsia
      case ElementCategory.postTransitionMetal:
        return const Color(0xFF334155); // Dark Slate
      case ElementCategory.lanthanide:
        return const Color(0xFF4338CA); // Muted Indigo
      case ElementCategory.actinide:
        return const Color(0xFF581C87); // Muted Purple
    }
  }
}

class PeriodicTable {
  static const Map<String, ElementInfo> elements = {
    'H': ElementInfo(
      symbol: 'H',
      nameEn: 'Hydrogen',
      nameFi: 'Vety',
      atomicNumber: 1,
      atomicMass: 1.008,
      typicalCharge: 1,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.structural,
      group: 1,
      period: 1,
      soilRoleEn: 'Determines soil pH. Essential for all organic molecules and water.',
      soilRoleFi: 'Määrittää maaperän pH-arvon. Välttämätön kaikille orgaanisille molekyyleille ja vedelle.',
    ),
    'He': ElementInfo(
      symbol: 'He',
      nameEn: 'Helium',
      nameFi: 'Helium',
      atomicNumber: 2,
      atomicMass: 4.0026,
      typicalCharge: 0,
      category: ElementCategory.nobleGas,
      agronomicRole: ElementAgronomicRole.inert,
      group: 18,
      period: 1,
      soilRoleEn: 'Inert noble gas. Atmospheric tracer in geochemical soil respiration studies.',
      soilRoleFi: 'Jalokaasu. Käytetään merkkiaineena maaperän kaasuvirtaus- ja hengitystutkimuksissa.',
    ),
    'Li': ElementInfo(
      symbol: 'Li',
      nameEn: 'Lithium',
      nameFi: 'Litium',
      atomicNumber: 3,
      atomicMass: 6.94,
      typicalCharge: 1,
      category: ElementCategory.alkaliMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 1,
      period: 2,
      soilRoleEn: 'Trace alkali metal. Can cause phytotoxicity at elevated concentrations.',
      soilRoleFi: 'Hivenalkalimetalli. Voi aiheuttaa kasvimyrkyllisyyttä suurina pitoisuuksina.',
    ),
    'Be': ElementInfo(
      symbol: 'Be',
      nameEn: 'Beryllium',
      nameFi: 'Beryllium',
      atomicNumber: 4,
      atomicMass: 9.0122,
      typicalCharge: 2,
      category: ElementCategory.alkalineEarthMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 2,
      period: 2,
      soilRoleEn: 'Rare trace metal. Strong mineral affinity, biologically toxic in soluble form.',
      soilRoleFi: 'Harvinainen maametalli. Sitoutuu vahvasti mineraaleihin; liukoisena myrkyllinen.',
    ),
    'B': ElementInfo(
      symbol: 'B',
      nameEn: 'Boron',
      nameFi: 'Boori',
      atomicNumber: 5,
      atomicMass: 10.81,
      typicalCharge: 3,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 13,
      period: 2,
      soilRoleEn: 'Essential micronutrient. Critical for cell wall cross-linking, membrane function, and pollen tube growth.',
      soilRoleFi: 'Välttämätön hivenravinne. Kriittinen soluseinien kalsiumsiltojen muodostumiselle ja siitepölyn itämiselle.',
    ),
    'C': ElementInfo(
      symbol: 'C',
      nameEn: 'Carbon',
      nameFi: 'Hiili',
      atomicNumber: 6,
      atomicMass: 12.011,
      typicalCharge: 4,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.structural,
      group: 14,
      period: 2,
      soilRoleEn: 'Backbone of Soil Organic Matter (SOM). Primary energy source for microbes via photosynthesis.',
      soilRoleFi: 'Maaperän orgaanisen aineksen (SOM) perusta ja mikrobiston tärkein energialähde yhteyttämisen kautta.',
    ),
    'N': ElementInfo(
      symbol: 'N',
      nameEn: 'Nitrogen',
      nameFi: 'Typpi',
      atomicNumber: 7,
      atomicMass: 14.007,
      typicalCharge: 5,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 15,
      period: 2,
      soilRoleEn: 'Primary macronutrient. Core component of amino acids, proteins, and chlorophyll.',
      soilRoleFi: 'Tärkein pääravinne. Proteiinien, nukleiinihappojen ja lehtivihreän (klorofylli) perusrakennusaine.',
    ),
    'O': ElementInfo(
      symbol: 'O',
      nameEn: 'Oxygen',
      nameFi: 'Happi',
      atomicNumber: 8,
      atomicMass: 15.999,
      typicalCharge: -2,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.structural,
      group: 16,
      period: 2,
      soilRoleEn: 'Drives soil redox potential and aerobic respiration by roots and microbes.',
      soilRoleFi: 'Määrää maaperän redox-potentiaalin ja mahdollistaa juurten sekä aerobisten mikrobien soluhengityksen.',
    ),
    'F': ElementInfo(
      symbol: 'F',
      nameEn: 'Fluorine',
      nameFi: 'Fluori',
      atomicNumber: 9,
      atomicMass: 18.998,
      typicalCharge: -1,
      category: ElementCategory.halogen,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 17,
      period: 2,
      soilRoleEn: 'Trace halogen. Bound in apatite minerals; soluble fluoride inhibits plant enzymes.',
      soilRoleFi: 'Halogeeni. Sitoutuu apatiittimineraaleihin; liukoinen fluoridi estää kasvien entsyymitoimintaa.',
    ),
    'Ne': ElementInfo(
      symbol: 'Ne',
      nameEn: 'Neon',
      nameFi: 'Neon',
      atomicNumber: 10,
      atomicMass: 20.18,
      typicalCharge: 0,
      category: ElementCategory.nobleGas,
      agronomicRole: ElementAgronomicRole.inert,
      group: 18,
      period: 2,
      soilRoleEn: 'Inert noble gas present in soil pore atmosphere.',
      soilRoleFi: 'Jalokaasu, esiintyy maahuokosten ilmakehässä reagoimattomana.',
    ),
    'Na': ElementInfo(
      symbol: 'Na',
      nameEn: 'Sodium',
      nameFi: 'Natrium',
      atomicNumber: 11,
      atomicMass: 22.99,
      typicalCharge: 1,
      category: ElementCategory.alkaliMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 1,
      period: 3,
      soilRoleEn: 'Beneficial in small amounts; excess causes soil dispersion, structural collapse, and sodicity.',
      soilRoleFi: 'Hyödyllinen pieninä määrinä; liika aiheuttaa maapartikkelien hajoamista, liettyvyyttä ja suolaantumista.',
    ),
    'Mg': ElementInfo(
      symbol: 'Mg',
      nameEn: 'Magnesium',
      nameFi: 'Magnesium',
      atomicNumber: 12,
      atomicMass: 24.305,
      typicalCharge: 2,
      category: ElementCategory.alkalineEarthMetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 2,
      period: 3,
      soilRoleEn: 'Secondary macronutrient. Central atom of chlorophyll and essential enzyme activator.',
      soilRoleFi: 'Pääravinne. Klorofyllimolekyylin keskusatomi sekä keskeinen entsyymien aktivaattori.',
    ),
    'Al': ElementInfo(
      symbol: 'Al',
      nameEn: 'Aluminium',
      nameFi: 'Alumiini',
      atomicNumber: 13,
      atomicMass: 26.982,
      typicalCharge: 3,
      category: ElementCategory.postTransitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 13,
      period: 3,
      soilRoleEn: 'Abundant soil mineral constituent. Becomes highly toxic (Al³⁺) to root tips at pH below 5.5.',
      soilRoleFi: 'Yleinen maamineraalien ainesosa. Muuttuu juurille erittäin myrkylliseksi (Al³⁺) alle pH 5,5:ssä.',
    ),
    'Si': ElementInfo(
      symbol: 'Si',
      nameEn: 'Silicon',
      nameFi: 'Pii',
      atomicNumber: 14,
      atomicMass: 28.085,
      typicalCharge: 4,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 14,
      period: 3,
      soilRoleEn: 'Beneficial element. Deposits in cell walls as phytoliths, enhancing lodging resistance and fungal defense.',
      soilRoleFi: 'Hyödyllinen alkuaine. Muodostaa fytoliitteja, jotka vahvistavat soluseiniä tauteja ja kuivuutta vastaan.',
    ),
    'P': ElementInfo(
      symbol: 'P',
      nameEn: 'Phosphorus',
      nameFi: 'Fosfori',
      atomicNumber: 15,
      atomicMass: 30.974,
      typicalCharge: 5,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 15,
      period: 3,
      soilRoleEn: 'Primary macronutrient. Drives energy transfer (ATP), DNA synthesis, and root branching.',
      soilRoleFi: 'Pääravinne. Välttämätön energian siirrossa (ATP), DNA-synteesissä ja juuriston kehityksessä.',
    ),
    'S': ElementInfo(
      symbol: 'S',
      nameEn: 'Sulfur',
      nameFi: 'Rikki',
      atomicNumber: 16,
      atomicMass: 32.06,
      typicalCharge: 6,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 16,
      period: 3,
      soilRoleEn: 'Secondary macronutrient. Essential for sulfur amino acids (methionine, cysteine) and nodulation.',
      soilRoleFi: 'Tärkeä pääravinne. Välttämätön rikkipitoisille aminohapoille (metioniini, kysteiini) ja typensidonnalle.',
    ),
    'Cl': ElementInfo(
      symbol: 'Cl',
      nameEn: 'Chlorine',
      nameFi: 'Kloori',
      atomicNumber: 17,
      atomicMass: 35.45,
      typicalCharge: -1,
      category: ElementCategory.halogen,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 17,
      period: 3,
      soilRoleEn: 'Essential micronutrient. Controls stomatal osmoregulation and photosystem II water splitting.',
      soilRoleFi: 'Välttämätön hivenravinne. Säätelee ilmarakojen osmoottista avautumista ja fotosysteemi II:n vesireaktiota.',
    ),
    'Ar': ElementInfo(
      symbol: 'Ar',
      nameEn: 'Argon',
      nameFi: 'Argon',
      atomicNumber: 18,
      atomicMass: 39.948,
      typicalCharge: 0,
      category: ElementCategory.nobleGas,
      agronomicRole: ElementAgronomicRole.inert,
      group: 18,
      period: 3,
      soilRoleEn: 'Atmospheric inert gas dissolved in soil solution; standard tracer for aeration.',
      soilRoleFi: 'Reagoimaton jalokaasu maahuokosissa; käytetään ilmanvaihdon vertailukaasuna.',
    ),
    'K': ElementInfo(
      symbol: 'K',
      nameEn: 'Potassium',
      nameFi: 'Kalium',
      atomicNumber: 19,
      atomicMass: 39.098,
      typicalCharge: 1,
      category: ElementCategory.alkaliMetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 1,
      period: 4,
      soilRoleEn: 'Primary macronutrient. Governs stomatal opening, cellular turgor pressure, and enzymatic activation.',
      soilRoleFi: 'Pääravinne. Säätelee ilmarakojen toimintaa, solujen turgorpainetta ja entsyymiaktiviteetteja.',
    ),
    'Ca': ElementInfo(
      symbol: 'Ca',
      nameEn: 'Calcium',
      nameFi: 'Kalsium',
      atomicNumber: 20,
      atomicMass: 40.078,
      typicalCharge: 2,
      category: ElementCategory.alkalineEarthMetal,
      agronomicRole: ElementAgronomicRole.macronutrient,
      group: 2,
      period: 4,
      soilRoleEn: 'Secondary macronutrient. Stabilizes cell walls, bridges soil clay aggregates (flocculation), and buffers pH.',
      soilRoleFi: 'Pääravinne. Vahvistaa soluseiniä, flokkuloi savihiukkasia kestäviksi muruiksi ja puskuroida happamuutta.',
    ),
    'Sc': ElementInfo(
      symbol: 'Sc',
      nameEn: 'Scandium',
      nameFi: 'Skandium',
      atomicNumber: 21,
      atomicMass: 44.956,
      typicalCharge: 3,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 3,
      period: 4,
      soilRoleEn: 'Trace transition metal tightly bound in silicate lattices.',
      soilRoleFi: 'Harvinainen siirtymämetalli, joka esiintyy sitoutuneena silikaattimineraaleihin.',
    ),
    'Ti': ElementInfo(
      symbol: 'Ti',
      nameEn: 'Titanium',
      nameFi: 'Titaani',
      atomicNumber: 22,
      atomicMass: 47.867,
      typicalCharge: 4,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 4,
      period: 4,
      soilRoleEn: 'Trace element. Can stimulate chlorophyll synthesis and enzymatic defense at low levels.',
      soilRoleFi: 'Hivenalkuaine. Voi stimuloida lehtivihreän muodostumista ja puolustusentsyymejä matalina pitoisuuksina.',
    ),
    'V': ElementInfo(
      symbol: 'V',
      nameEn: 'Vanadium',
      nameFi: 'Vanadiini',
      atomicNumber: 23,
      atomicMass: 50.942,
      typicalCharge: 5,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 5,
      period: 4,
      soilRoleEn: 'Beneficial trace element. Acts as an alternative cofactor in nitrogenase enzyme systems.',
      soilRoleFi: 'Hyödyllinen hivenaine. Toimii vaihtoehtoisena kofaktorina typensidonnan nitrogenaasientsyymeissä.',
    ),
    'Cr': ElementInfo(
      symbol: 'Cr',
      nameEn: 'Chromium',
      nameFi: 'Kromi',
      atomicNumber: 24,
      atomicMass: 51.996,
      typicalCharge: 3,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 6,
      period: 4,
      soilRoleEn: 'Heavy metal. Cr(VI) is a potent soil toxicant and carcinogen; Cr(III) is insoluble and less toxic.',
      soilRoleFi: 'Raskasmetalli. Kuudenarvoinen kromi Cr(VI) on erittäin myrkyllinen; Cr(III) sitoutuu voimakkaasti maahan.',
    ),
    'Mn': ElementInfo(
      symbol: 'Mn',
      nameEn: 'Manganese',
      nameFi: 'Mangaani',
      atomicNumber: 25,
      atomicMass: 54.938,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 7,
      period: 4,
      soilRoleEn: 'Essential micronutrient. Catalyzes water oxidation in Photosystem II and activates decarboxylases.',
      soilRoleFi: 'Välttämätön hivenravinne. Katalysoi veden hajotusta fotosysteemi II:ssa ja aktivoi aineenvaihduntaentsyymejä.',
    ),
    'Fe': ElementInfo(
      symbol: 'Fe',
      nameEn: 'Iron',
      nameFi: 'Rauta',
      atomicNumber: 26,
      atomicMass: 55.845,
      typicalCharge: 3,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 8,
      period: 4,
      soilRoleEn: 'Essential micronutrient. Critical for heme proteins, electron transport chains, and chlorophyll synthesis.',
      soilRoleFi: 'Välttämätön hivenravinne. Keskeinen elektroninsiirtoketjuissa (sitokromit), soluhengityksessä ja klorofyllissä.',
    ),
    'Co': ElementInfo(
      symbol: 'Co',
      nameEn: 'Cobalt',
      nameFi: 'Koboltti',
      atomicNumber: 27,
      atomicMass: 58.933,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 9,
      period: 4,
      soilRoleEn: 'Essential for symbiotic nitrogen fixation by Rhizobium bacteria (vitamin B12 cobalamin).',
      soilRoleFi: 'Välttämätön Rhizobium-nystyräbakteerien biologiselle typensidonnalle (B12-vitamiinin kobalamiini).',
    ),
    'Ni': ElementInfo(
      symbol: 'Ni',
      nameEn: 'Nickel',
      nameFi: 'Nikkeli',
      atomicNumber: 28,
      atomicMass: 58.693,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 10,
      period: 4,
      soilRoleEn: 'Essential micronutrient. Active catalytic center of the urease enzyme, converting urea into ammonium.',
      soilRoleFi: 'Välttämätön hivenravinne. Ureaasientsyymin katalyyttinen keskus, joka muuttaa urean kasveille ammoniumiksi.',
    ),
    'Cu': ElementInfo(
      symbol: 'Cu',
      nameEn: 'Copper',
      nameFi: 'Kupari',
      atomicNumber: 29,
      atomicMass: 63.546,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 11,
      period: 4,
      soilRoleEn: 'Essential micronutrient. Component of plastocyanin in photosynthesis and polyphenol oxidase in lignin synthesis.',
      soilRoleFi: 'Välttämätön hivenravinne. Fotosynteesin plastosyaniinin ja soluseinien ligniinisynteesin kofaktori.',
    ),
    'Zn': ElementInfo(
      symbol: 'Zn',
      nameEn: 'Zinc',
      nameFi: 'Sinkki',
      atomicNumber: 30,
      atomicMass: 65.38,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 12,
      period: 4,
      soilRoleEn: 'Essential micronutrient. Mandatory for auxin (IAA) hormone synthesis, RNA polymerase, and ribosome integrity.',
      soilRoleFi: 'Välttämätön hivenravinne. Vaaditaan auksiinihormonin (IAA) synteesiin, entsyymeille ja ribosomien toiminnalle.',
    ),
    'Ga': ElementInfo(
      symbol: 'Ga',
      nameEn: 'Gallium',
      nameFi: 'Gallium',
      atomicNumber: 31,
      atomicMass: 69.723,
      typicalCharge: 3,
      category: ElementCategory.postTransitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 13,
      period: 4,
      soilRoleEn: 'Trace metal substituting for aluminum and iron in mineral structures.',
      soilRoleFi: 'Harvinainen maametalli, esiintyy mineraaleissa korvaten alumiinia tai rautaa.',
    ),
    'Ge': ElementInfo(
      symbol: 'Ge',
      nameEn: 'Germanium',
      nameFi: 'Germanium',
      atomicNumber: 32,
      atomicMass: 72.63,
      typicalCharge: 4,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.inert,
      group: 14,
      period: 4,
      soilRoleEn: 'Trace metalloid exhibiting geochemical behavior similar to silicon.',
      soilRoleFi: 'Puolimetalli, joka käyttäytyy maaperän geokemiassa piin tavoin.',
    ),
    'As': ElementInfo(
      symbol: 'As',
      nameEn: 'Arsenic',
      nameFi: 'Arseeni',
      atomicNumber: 33,
      atomicMass: 74.922,
      typicalCharge: 5,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 15,
      period: 4,
      soilRoleEn: 'Toxic metalloid contaminant. Competes with phosphate for uptake and disrupts ATP phosphorylation.',
      soilRoleFi: 'Myrkyllinen puolimetalli ja maaperäsaaste. Kilpailee fosfaatin otossa ja häiritsee ATP-fosforylaatiota.',
    ),
    'Se': ElementInfo(
      symbol: 'Se',
      nameEn: 'Selenium',
      nameFi: 'Seleeni',
      atomicNumber: 34,
      atomicMass: 78.971,
      typicalCharge: 4,
      category: ElementCategory.nonmetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 16,
      period: 4,
      soilRoleEn: 'Beneficial trace element. Promotes glutathione peroxidase antioxidant activity protecting from drought.',
      soilRoleFi: 'Hyödyllinen hivenalkuaine. Stimuloi glutationiperoksidaasin antioksidanttisuojaa kuivuutta vastaan.',
    ),
    'Br': ElementInfo(
      symbol: 'Br',
      nameEn: 'Bromine',
      nameFi: 'Bromi',
      atomicNumber: 35,
      atomicMass: 79.904,
      typicalCharge: -1,
      category: ElementCategory.halogen,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 17,
      period: 4,
      soilRoleEn: 'Trace halogen in coastal soils. High concentrations inhibit root tissue respiration.',
      soilRoleFi: 'Halogeeni rannikkomailla. Suuret pitoisuudet heikentävät juuriston hengitystä.',
    ),
    'Kr': ElementInfo(
      symbol: 'Kr',
      nameEn: 'Krypton',
      nameFi: 'Krypton',
      atomicNumber: 36,
      atomicMass: 83.798,
      typicalCharge: 0,
      category: ElementCategory.nobleGas,
      agronomicRole: ElementAgronomicRole.inert,
      group: 18,
      period: 4,
      soilRoleEn: 'Heavy inert noble gas used for soil pore tortuosity and diffusion analysis.',
      soilRoleFi: 'Raskas jalokaasu, jota käytetään maaperän huokoisuuden ja kaasudiffuusion mallinnuksessa.',
    ),
    'Rb': ElementInfo(
      symbol: 'Rb',
      nameEn: 'Rubidium',
      nameFi: 'Rubidium',
      atomicNumber: 37,
      atomicMass: 85.468,
      typicalCharge: 1,
      category: ElementCategory.alkaliMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 1,
      period: 5,
      soilRoleEn: 'Alkali metal mimicking potassium uptake; non-toxic in natural soil background amounts.',
      soilRoleFi: 'Alkalimetalli, joka muistuttaa kaliumia kasvien otossa; vaaraton luonnollisina pitoisuuksina.',
    ),
    'Sr': ElementInfo(
      symbol: 'Sr',
      nameEn: 'Strontium',
      nameFi: 'Strontium',
      atomicNumber: 38,
      atomicMass: 87.62,
      typicalCharge: 2,
      category: ElementCategory.alkalineEarthMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 2,
      period: 5,
      soilRoleEn: 'Alkaline earth metal closely tracking calcium geochemical pathways in soil solution.',
      soilRoleFi: 'Maa-alkalimetalli, joka seuraa maaliuoksessa kalsiumin geokemiallisia reittejä.',
    ),
    'Y': ElementInfo(
      symbol: 'Y',
      nameEn: 'Yttrium',
      nameFi: 'Yttrium',
      atomicNumber: 39,
      atomicMass: 88.906,
      typicalCharge: 3,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 3,
      period: 5,
      soilRoleEn: 'Rare earth transition metal strongly adsorbed on clay surfaces and organic matter.',
      soilRoleFi: 'Harvinainen siirtymämetalli, joka sitoutuu tiukasti savipinnoille ja humukseen.',
    ),
    'Zr': ElementInfo(
      symbol: 'Zr',
      nameEn: 'Zirconium',
      nameFi: 'Zirkonium',
      atomicNumber: 40,
      atomicMass: 91.224,
      typicalCharge: 4,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 4,
      period: 5,
      soilRoleEn: 'Extremely weather-resistant mineral constituent (zircon) used as pedogenic weathering index.',
      soilRoleFi: 'Erittäin säänkestävä mineraaliainesosa (zirkoni); käytetään maannoksen iän ja rapautumisen mittarina.',
    ),
    'Nb': ElementInfo(
      symbol: 'Nb',
      nameEn: 'Niobium',
      nameFi: 'Niobium',
      atomicNumber: 41,
      atomicMass: 92.906,
      typicalCharge: 5,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 5,
      period: 5,
      soilRoleEn: 'Refractory transition metal with very low bioavailability in soil solution.',
      soilRoleFi: 'Sitkeä siirtymämetalli, jonka biologinen hyödynnettävyys maassa on minimaalinen.',
    ),
    'Mo': ElementInfo(
      symbol: 'Mo',
      nameEn: 'Molybdenum',
      nameFi: 'Molybdeeni',
      atomicNumber: 42,
      atomicMass: 95.95,
      typicalCharge: 6,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.micronutrient,
      group: 6,
      period: 5,
      soilRoleEn: 'Essential micronutrient. Core catalytic cofactor of nitrogenase (N₂ fixation) and nitrate reductase.',
      soilRoleFi: 'Välttämätön hivenravinne. Typensidonnan (nitrogenaasi) ja nitraatin pelkistyksen keskeinen kofaktori.',
    ),
    'Tc': ElementInfo(
      symbol: 'Tc',
      nameEn: 'Technetium',
      nameFi: 'Teknetium',
      atomicNumber: 43,
      atomicMass: 98.0,
      typicalCharge: 7,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 7,
      period: 5,
      soilRoleEn: 'Synthetic radioactive element; environmentally monitored in nuclear soil safety.',
      soilRoleFi: 'Synteettinen radioaktiivinen alkuaine; seurataan ympäristö- ja säteilyturvallisuudessa.',
    ),
    'Ru': ElementInfo(
      symbol: 'Ru',
      nameEn: 'Ruthenium',
      nameFi: 'Ruteeni',
      atomicNumber: 44,
      atomicMass: 101.07,
      typicalCharge: 4,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 8,
      period: 5,
      soilRoleEn: 'Platinum-group metal tightly stabilized in refractory mineral fractions.',
      soilRoleFi: 'Platinametalli, joka pysyy maaperässä erittäin stabiilina ja liukenemattomana.',
    ),
    'Rh': ElementInfo(
      symbol: 'Rh',
      nameEn: 'Rhodium',
      nameFi: 'Rodium',
      atomicNumber: 45,
      atomicMass: 102.91,
      typicalCharge: 3,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 9,
      period: 5,
      soilRoleEn: 'Inert precious metal with negligible mobility in soil.',
      soilRoleFi: 'Reagoimaton jalometalli, jolla ei ole merkittävää liikkuvuutta maassa.',
    ),
    'Pd': ElementInfo(
      symbol: 'Pd',
      nameEn: 'Palladium',
      nameFi: 'Palladium',
      atomicNumber: 46,
      atomicMass: 106.42,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 10,
      period: 5,
      soilRoleEn: 'Trace catalytic metal accumulating from traffic runoff; binds tightly to humic substances.',
      soilRoleFi: 'Katalysaattorisaasteena kertyvä jalometalli; sitoutuu tiukasti humukseen.',
    ),
    'Ag': ElementInfo(
      symbol: 'Ag',
      nameEn: 'Silver',
      nameFi: 'Hopea',
      atomicNumber: 47,
      atomicMass: 107.87,
      typicalCharge: 1,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 11,
      period: 5,
      soilRoleEn: 'Antimicrobial metal ion (Ag⁺) inhibiting soil bacterial respiration and enzyme activity at high levels.',
      soilRoleFi: 'Antimikrobinen metalli-ioni (Ag⁺), joka estää maabakteerien hengitystä ja entsyymitoimintaa liikaa esiintyessään.',
    ),
    'Cd': ElementInfo(
      symbol: 'Cd',
      nameEn: 'Cadmium',
      nameFi: 'Kadmium',
      atomicNumber: 48,
      atomicMass: 112.41,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 12,
      period: 5,
      soilRoleEn: 'Hazardous heavy metal pollutant. Readily absorbed by roots, displacing zinc and causing severe cellular damage.',
      soilRoleFi: 'Vaarallinen raskasmetallisaaste. Siirtyy helposti juuriin, syrjäyttää sinkin ja vaurioittaa solurakenteita.',
    ),
    'In': ElementInfo(
      symbol: 'In',
      nameEn: 'Indium',
      nameFi: 'Indium',
      atomicNumber: 49,
      atomicMass: 114.82,
      typicalCharge: 3,
      category: ElementCategory.postTransitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 13,
      period: 5,
      soilRoleEn: 'Trace technology metal exhibiting low environmental mobility in neutral soils.',
      soilRoleFi: 'Teknologiametalli, jolla on vähäinen ympäristöliikkuvuus neutraaleissa maissa.',
    ),
    'Sn': ElementInfo(
      symbol: 'Sn',
      nameEn: 'Tin',
      nameFi: 'Tina',
      atomicNumber: 50,
      atomicMass: 118.71,
      typicalCharge: 4,
      category: ElementCategory.postTransitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 14,
      period: 5,
      soilRoleEn: 'Post-transition metal forming stable, insoluble oxides (cassiterite) in soils.',
      soilRoleFi: 'Metalli, joka muodostaa maaperässä erittäin stabiileja, liukenemattomia oksideja.',
    ),
    'Sb': ElementInfo(
      symbol: 'Sb',
      nameEn: 'Antimony',
      nameFi: 'Antimoni',
      atomicNumber: 51,
      atomicMass: 121.76,
      typicalCharge: 5,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 15,
      period: 5,
      soilRoleEn: 'Toxic metalloid resembling arsenic; geochemical contaminant near industrial sites.',
      soilRoleFi: 'Arseenin kaltainen myrkyllinen puolimetalli ja teollisuusalueiden maaperäsaaste.',
    ),
    'Te': ElementInfo(
      symbol: 'Te',
      nameEn: 'Tellurium',
      nameFi: 'Telluuri',
      atomicNumber: 52,
      atomicMass: 127.6,
      typicalCharge: 4,
      category: ElementCategory.metalloid,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 16,
      period: 5,
      soilRoleEn: 'Rare metalloid; bioaccumulates in fungi and microbes via sulfur transport pathways.',
      soilRoleFi: 'Harvinainen puolimetalli, jota mikrobit ja sienet voivat ottaa rikin kuljetusreittejä pitkin.',
    ),
    'I': ElementInfo(
      symbol: 'I',
      nameEn: 'Iodine',
      nameFi: 'Jodi',
      atomicNumber: 53,
      atomicMass: 126.9,
      typicalCharge: -1,
      category: ElementCategory.halogen,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 17,
      period: 5,
      soilRoleEn: 'Essential for mammalian biology and beneficial to plants; tightly sorbed by soil organic matter.',
      soilRoleFi: 'Eläimille elintärkeä ja kasveille hyödyllinen halogeeni; sitoutuu vahvasti maaperän humukseen.',
    ),
    'Xe': ElementInfo(
      symbol: 'Xe',
      nameEn: 'Xenon',
      nameFi: 'Ksenon',
      atomicNumber: 54,
      atomicMass: 131.29,
      typicalCharge: 0,
      category: ElementCategory.nobleGas,
      agronomicRole: ElementAgronomicRole.inert,
      group: 18,
      period: 5,
      soilRoleEn: 'Heavy noble gas used as inert tracer for deep groundwater recharge and gas diffusion.',
      soilRoleFi: 'Raskas jalokaasu, jota käytetään merkkiaineena pohjavesivirtauksissa ja kaasudiffuusiossa.',
    ),
    'Cs': ElementInfo(
      symbol: 'Cs',
      nameEn: 'Caesium',
      nameFi: 'Cesium',
      atomicNumber: 55,
      atomicMass: 132.91,
      typicalCharge: 1,
      category: ElementCategory.alkaliMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 1,
      period: 6,
      soilRoleEn: 'Alkali metal. Cs-137 radionuclide binds strongly to illite clay interlayers.',
      soilRoleFi: 'Alkalimetalli. Radioisotooppi Cs-137 sitoutuu voimakkaasti illiittisaven välikerroksiin.',
    ),
    'Ba': ElementInfo(
      symbol: 'Ba',
      nameEn: 'Barium',
      nameFi: 'Barium',
      atomicNumber: 56,
      atomicMass: 137.33,
      typicalCharge: 2,
      category: ElementCategory.alkalineEarthMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 2,
      period: 6,
      soilRoleEn: 'Heavy alkaline earth metal precipitated as insoluble barite (BaSO₄) in sulfur-rich soils.',
      soilRoleFi: 'Raskas maa-alkalimetalli, saostuu maaperässä liukenemattomana baryyttina (BaSO₄).',
    ),
    'W': ElementInfo(
      symbol: 'W',
      nameEn: 'Tungsten',
      nameFi: 'Volframi',
      atomicNumber: 74,
      atomicMass: 183.84,
      typicalCharge: 6,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.beneficial,
      group: 6,
      period: 6,
      soilRoleEn: 'Heavy transition metal; acts as hyperthermophilic microbial enzyme cofactor substituting for Mo.',
      soilRoleFi: 'Raskas siirtymämetalli; toimii eräissä mikrobientsyymeissä molybdeenin korvaajana.',
    ),
    'Pt': ElementInfo(
      symbol: 'Pt',
      nameEn: 'Platinum',
      nameFi: 'Platina',
      atomicNumber: 78,
      atomicMass: 195.08,
      typicalCharge: 4,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 10,
      period: 6,
      soilRoleEn: 'Inert noble metal catalyst with negligible biological cycling in soil.',
      soilRoleFi: 'Jalometalli ja teollinen katalyytti, jolla ei ole merkittävää biologista kiertoa maassa.',
    ),
    'Au': ElementInfo(
      symbol: 'Au',
      nameEn: 'Gold',
      nameFi: 'Kulta',
      atomicNumber: 79,
      atomicMass: 196.97,
      typicalCharge: 1,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.inert,
      group: 11,
      period: 6,
      soilRoleEn: 'Chemically inert noble metal; solubilized exclusively by specific bacterial cyanide complexes.',
      soilRoleFi: 'Reagoimaton jalometalli; liukenee maassa vain harvojen bakteerien syanidikomplekseihin.',
    ),
    'Hg': ElementInfo(
      symbol: 'Hg',
      nameEn: 'Mercury',
      nameFi: 'Elohopea',
      atomicNumber: 80,
      atomicMass: 200.59,
      typicalCharge: 2,
      category: ElementCategory.transitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 12,
      period: 6,
      soilRoleEn: 'Highly toxic heavy metal pollutant. Anaerobic microbes methylate it into bioaccumulating methylmercury.',
      soilRoleFi: 'Erittäin vaarallinen raskasmetallisaaste. Anaerobiset bakteerit metyloivat sen ravintoketjussa kertyväksi metyylielohopeaksi.',
    ),
    'Pb': ElementInfo(
      symbol: 'Pb',
      nameEn: 'Lead',
      nameFi: 'Lyijy',
      atomicNumber: 82,
      atomicMass: 207.2,
      typicalCharge: 2,
      category: ElementCategory.postTransitionMetal,
      agronomicRole: ElementAgronomicRole.toxic,
      group: 14,
      period: 6,
      soilRoleEn: 'Persistent heavy metal pollutant. Binds strongly to soil organics and carbonates, impairing root cell elongation.',
      soilRoleFi: 'Pysyvä raskasmetallisaaste. Sitoutuu vahvasti humukseen ja karbonaatteihin, vahingoittaen juurisoluja.',
    ),
  };

  /// Precomputed position index for O(1) grid lookups.
  static final Map<String, ElementInfo> _byCoord = {
    for (final e in elements.values) '${e.period}_${e.group}': e,
  };

  /// Returns element at given period (1-7) and group (1-18), if available.
  static ElementInfo? getByPosition(int period, int group) {
    return _byCoord['${period}_$group'];
  }

  /// Returns element by chemical symbol, or null if not found.
  static ElementInfo? getBySymbol(String symbol) {
    return elements[symbol];
  }

  static ElementInfo getElement(String symbol) {
    return elements[symbol] ?? elements['H']!;
  }
}
